(function($) {
	var lims = window.lims = window.lims || {};

	if (!lims.zh) {
		lims.zh = {};
	}

	$.extend(true, lims.zh, {
		"upload_facility_files":"请上传设备信息图片",
		"Food info":"产品信息",
		"Bar code":"条形码",
		"food_Name":"名称",
		"Specification":"规格",
		"Model No":"型号",
		"Brand":"商标",
		"Standard":"执行标准",
		"Expiratio":"质保期",
		"Expir Day":"保质天数",
		"foodInfo_address":"产地",
		"foodInfo_Status":"商品状态",
		"ProductPhotos":"产品图片",
		"upload_ProdPhoto":"上传产品图片",
		"Business Unit Info":"生产企业信息",
		"License No":"营业执照号",
		"QS No":"生产许可证号",
		"Can Choose BusName":"可选生产企业",
		"business_Name":"生产企业名称",
		"Address":"生产企业地址",
		"Testee Info":"经销商信息",
		"Regist No":"经营主体注册号",
		"Company":"备案公司名称",
		"testee_Name":"负责人名称",
		"ID Card":"负责人身份证号",
		"Tel":"负责人手机号码",
		"testee_Address":"负责人通讯地址",
		"Test Report Info":"检测报告信息",
		"ReportNo":"报告编号",
		"Testee":"被检测单位/人",
		"Test Org":"检验单位名称",
		"Test Type":"检验类别",
		"Conclusio":"检验结论",
		"Test place":"检验地点",
		"Prod Date":"生产日期",
		"Test Date":"检验日期",
		"Batch":"批次号",
		"End Date":"有效期至",
		"sampleAddress":"抽样地点",
		"sampleCounts":"抽样量",
		"judgeStandard":"执行标准",
		"testResultDescribe":"检验结论描述",
		"remarks":"备注",
		"backResult":"退回原因",
		"isAutoReport":"是否自动生成报告",
		"isAutoReport_ts":'(当无扫描版报告上传时，可选择"是")',
		"yesAuto":"是",
		"noAuto":"否",
		"Report":"报告",
		"upload_report_files":"上传pdf",
		"upload_report_img":"上传报告原件图片",
		"upload_check_img":"上传检测凭证图片",
		"upload_buy_img":"上传购买凭证图片",
		"uploadRepPics":"上传报告图片",
		"upload_prodPhoto_btn":"上传产品图片",
		"up_ex_file":"选择excel文件",
		"upload_cert":"上传认证图片",
		"upload_propaganda":"上传企业宣传照",
		"upload_tax":"上传税务登记证",
		"upload_qr":"上传企业二维码",
		"upload_honorIcon":"上传荣誉小图标",
		"Add Item":"添加",
	    "submit":"提交",
	    "set_template":"设为模版",
	    
	    "Item Name":"检测项目名称",
	    "Unit":"单位",
	    "Specifications":"技术指标",
	    "Test Result":"检测结果",
	    "Conslusion":"单项评价",
	    "Standard_":"检测依据",
	    "Operation":"操作",
	    "Delete":"删除",
		"Edit":"编辑",
	    "Category" : "产品类别",
	    "Year":"年",
	    "Month":"月",
	    "Day":"天",
	    "expirdayTS":"（根据保质期中的年月日自动计算）",
	    "Save Status":"正在提交，请稍候...",
	    
	    //publish页面
	    "Publish":"发布",
	    "Report No":"报告编号",
	    "Product Name":"报告名称",
	    "Production Date":"生产日期",
	    "Batch":"批次",
	    "Test Organization":"检测机构",
	    "edit":"编辑",
	    "Review":"预览",
	    "Review Pdf":"预览pdf",
	    "Resource is null, send failure!":"没有资源文件，上传失败！",
	    "res_type" : "文件类型",
	    "OK":"确定",
	    "Cancel":"取消",
	    "delResMsg":"文件将会被永久删除，确定要继续吗？",
	    "delItemMsg":"检测项目将会被永久删除，确定要继续吗？",
	    "remarkText":"请填写关于该报告的备注信息",
	    "Are you sure to delete registration form" : "确定需要删除这条报告吗？",
	    "saveResMsg" : "由于当前报告没有上传产品图片，会导致发布报告时用一张临时图片代替。可以点击取消后，上传相关产品图片；也可以点击确定，先保存报告信息，之后再编辑添加。",
	    "noProResMsg" : "当前报告无产品图片！点击确定后，会用一张临时图片代替。",
	    
	    //add_js
	    "Product Information Bar has required Unfilled":"【产品信息】栏有必填项未填",
	    "Manufacturers have required information bar unfilled":"【生产企业信息】栏有必填项未填",
	    "Test report required information fields have not filled":"【检测报告信息】栏有必填项未填",
	    "Please enter a business license number":"请输入营业执照号",
	    "can not contain illegal characters, only by the Chinese, letters, numbers or underscores":"不能包含非法字符,只能由中文、字母、数字或下划线组成",
	    "can not contain “'”、“?” illegal characters!":"不能包含单引号【'】、问号【?】两种非法字符！",
	    "Can only contain letters and numbers!":"只能包含字母和数字且只能是13或15位!",
	    "can not contain Chinese characters!":"不能报告中文！",
	    "QS card number":"QS证号",
	    "Business license number":"营业执照号",
	    "Please enter the report number":"请输入报告编号",
	    "Report Number":"报告编号",
	    "Wrong file type, the file will not be saved and re-upload pdf format Please delete!":"文件类型有误，该文件不会被保存，请删除后重新上传pdf格式文件！",
	    "Wrong file type, the file will not be saved, please delete the re-upload png, bmp, jpeg file format!":"文件类型有误，该文件不会被保存，请删除重新上传pdf、png、bmp、jpeg格式的文件!",
	    "Wrong file type, the file will not be saved and re-upload png、bmp、jpeg format Please delete!":"文件类型有误，该文件不会被保存，请删除重新上传png、bmp、jpeg格式的文件!",
	    "The file you uploaded mismatching template, re-upload the file in pdf format Please delete!":"由于文件无法匹配现有的pdf模板，所以该文件不会被保存，请删除后重新上传pdf格式文件！",
	    "The file you uploaded mismatching product, re-upload the file in pdf format Please delete!":"由于文件无法匹配到一条产品信息，所以该文件不会被保存，请删除后重新上传pdf格式文件！",
	    "The report you uploaded has existed, re-upload the file in pdf format Please delete!":"由于文件对应的报告已经存在，所以该文件不会被保存，请删除后重新上传pdf格式文件！",
	    "The file you uploaded more than 10M, re-upload the file in pdf format Please delete!":"您上传的文件已经超过10M，请删除后重新上传pdf格式的文件！",
	    "The file you uploaded more than 10M, re-upload, delete png, bmp, jpeg file format!":"您上传的文件已经超过10M，请删除后重新上传png、bmp、jpeg格式的文件!",
	    "The file you uploaded more than 10M, re-upload the file in png、bmp、jpeg format Please delete!":"您上传的文件已经超过10M，请删除后重新上传png、bmp、jpeg格式的文件!",
	    "Document recognition is successful, you can save!":"文件识别成功，可以保存！",
	    "Note: The file size can not exceed 10M! Supported file formats: png, bmp, jpeg":"注意:每个文件大小不能超过10M！  可支持的文件格式：png .bmp .jpeg .jpg！",
	    "Note: The file size can not exceed 10M! Only supports file formats: pdf":"注意:每个文件大小不能超过10M！  当前只支持文件格式.pdf",
	    "Note: The file size can not exceed 10M! Supported file formats: png, bmp, jpeg":"注意:文件大小不能超过10M！  可支持的文件格式：png .bmp .jpeg .jpg！",
	    "An exception occurred while uploading the file! Please try again later ...":"上传文件时出现异常！请稍候再试...",
	    "upload_brandPhoto": "上传商标图片",
	    "not found pdf":"您当前还没有上传检测报告，若需要自动生成pdf，请将【是否自动生成报告】选项设置为“是”！",
	    "auto create pdf":"当前【是否自动生成报告】选项的状态为“是”，如果您需要自动生成报告，请将已有的检测报告删除！",
	    "pdf more then":"检测报告pdf只能上传一份！",
	    "The BusinessName is null":"生产企业名称不能为空，请先完整填写本企业的信息。",
	    "You can not modify this product's barcode information, please change the barcode":"您不能修改此商品的条形码信息，请将条形码更改为",
	    "Current product information is empty, Please select the product after trying to save barcode search!":"当前产品信息为空，请通过条形码搜索自动加载产品信息后，再尝试提交！",
	    "QS card number can not be empty":"QS证号不能为空",
	    "Business license number is not in the correct format, must be composed of letters or numbers 13 or 15.":"营业执照号格式不正确，必须是由13位或者15位的字母或数字组成",
	    
	    //预览窗口
	    "View Product":"产品信息预览",
	    "View Busunit":"生产企业信息预览",
	    "View Testee":"经销商信息预览",
	    "View Report":"检测报告信息预览",
	    "Registration time format is incorrect":"注册时间的格式不正确！(例如：2013-01-01)",
	    "Test report format is not valid!":"检测报告【有效期至】格式不对！",
	});
	
	$(document).ready(function() {
		lims.updateLocale();
	});
})(jQuery);