//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 03:22:00 PM PDT 
//


package com.gettec.fsnip.fsn.model.test;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.gettec.fsnip.fsn.model.test package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestResult_QNAME = new QName("http://www.gettec.cn/fsn/test", "Report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gettec.fsnip.fsn.model.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestResult }
     * 
     */
    public TestResult createTestResult() {
        return new TestResult();
    }

    /**
     * Create an instance of {@link TestProperty }
     * 
     */
    public TestProperty createTestProperty() {
        return new TestProperty();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gettec.cn/fsn/test", name = "Report")
    public JAXBElement<TestResult> createReport(TestResult value) {
        return new JAXBElement<TestResult>(_TestResult_QNAME, TestResult.class, null, value);
    }

}
