//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-313 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.19 at 03:22:00 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gettec.cn/fsn/test", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gettec.fsnip.fsn.model.test;
