DROP TABLE area;
DROP TABLE additive;
DROP TABLE business_category;
DROP TABLE business_unit_test;
DROP TABLE complain;
DROP TABLE consignment;
DROP TABLE consignment_product;
DROP TABLE event_report;
DROP TABLE fda_dependency;
DROP TABLE fda_statement;
DROP TABLE fda_test;
ALTER TABLE `product` DROP FOREIGN KEY `fk_product_fda_product_group`;
commit;
ALTER TABLE `product` DROP COLUMN `fda_product_group`;
ALTER TABLE `test_result` DROP FOREIGN KEY `fk_test_result_fda_test_plan`;
commit;
ALTER TABLE `test_result` DROP COLUMN `fda_test_plan_id`;
DROP TABLE fda_test_plan;
DROP TABLE fda_product_group;
DROP TABLE fda;
DROP TABLE foodcat;
DROP TABLE fsn_comment;
DROP TABLE fsn_display;
DROP TABLE fsn_display_ad;
DROP TABLE fsn_display_col;
DROP TABLE fsn_display_news;
DROP TABLE fsn_display_prod;
DROP TABLE fsn_display_uri;
DROP TABLE fsn_display_re;
DROP TABLE fsn_user;
DROP TABLE manu_equipment;
DROP TABLE manu_quipment;
DROP TABLE message;
DROP TABLE onsite_verification;
DROP TABLE parent_product_to_test_item;
DROP TABLE test_item;
DROP TABLE parent_product;
DROP TABLE product_auth;
DROP TABLE product_info;
DROP TABLE product_invoice;
DROP TABLE product_invoice_detail;
DROP TABLE product_ledger;
DROP TABLE product_poll;
DROP TABLE product_purchase;
DROP TABLE product_sale;
DROP TABLE product_storage;
DROP TABLE production_license;
DROP TABLE qat_material;
DROP TABLE qat_product;
DROP TABLE qat_self_test;
DROP TABLE qat_self_test_basic;
DROP TABLE qat_unqualified_issue;
DROP TABLE qs_annual_test;
DROP TABLE routine_test;
DROP TABLE seasoning_additive;
DROP TABLE seasoning_base;
DROP TABLE service_certification;
DROP TABLE special_plan;
DROP TABLE special_task;
DROP TABLE staff;
DROP TABLE t_batch_sample;
DROP TABLE test_case;
DROP TABLE test_cycle;
DROP TABLE test_lab_test;
DROP TABLE test_equipment;
DROP TABLE test_quipment;
DROP TABLE testa;
DROP TABLE testb;
DROP TABLE unqualified_issue;
DROP TABLE user;
DROP TABLE users;
DROP TABLE zhcc_task;
DROP TABLE zhcc_plan;



