ALTER TABLE `t_test_temp_busunit`
DROP COLUMN `ORG_NAME`,
ADD COLUMN `ORGANIZATION`  bigint(20) NOT NULL AFTER `LAST_MODIFY_TIME`;

ALTER TABLE `t_test_temp_product`
DROP COLUMN `ORG_NAME`,
ADD COLUMN `ORGANIZATION`  bigint(20) NOT NULL AFTER `LAST_MODIFY_TIME`;

ALTER TABLE `t_test_temp_report`
DROP COLUMN `ORG_NAME`,
ADD COLUMN `ORGANIZATION`  bigint(20) NOT NULL AFTER `LAST_MODIFY_TIME`;