
ALTER TABLE `business_unit`
ADD COLUMN `PROVIDER_TYPE_ID`  int NULL AFTER `orgnization`;


ALTER TABLE `business_unit`
ADD COLUMN `CUSTOMER_TYPE_ID`  int NULL AFTER `PROVIDER_TYPE_ID`;

ALTER TABLE `business_unit`
ADD COLUMN `CUSTOMER_OR_PROVIDER_TYPE`  int NULL COMMENT '1代表客户，2代表供应商' AFTER `CUSTOMER_TYPE_ID`;

ALTER TABLE `business_unit` ADD CONSTRAINT `business_unit_fk1` FOREIGN KEY (`PROVIDER_TYPE_ID`) REFERENCES `t_meta_provider_type` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `business_unit` ADD CONSTRAINT `business_unit_fk2` FOREIGN KEY (`CUSTOMER_TYPE_ID`) REFERENCES `t_meta_customer_type` (`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `business_unit`
MODIFY COLUMN `PROVIDER_TYPE_ID`  int(11) NULL DEFAULT NULL COMMENT '供应商id' AFTER `orgnization`;

ALTER TABLE `business_unit`
MODIFY COLUMN `CUSTOMER_TYPE_ID`  int(11) NULL DEFAULT NULL COMMENT '客户id' AFTER `PROVIDER_TYPE_ID`;

ALTER TABLE `business_unit`
MODIFY COLUMN `CUSTOMER_OR_PROVIDER_TYPE`  int(11) NULL DEFAULT NULL COMMENT '1代表客户，2代表供应商' AFTER `CUSTOMER_TYPE_ID`;

