ALTER TABLE `t_test_temp_product`
ADD COLUMN `CATEGORYPARENTID`  bigint(20) NULL COMMENT '二级分类ID' AFTER `ORGANIZATION`,
ADD COLUMN `CATEGORYPARENTCODE`  varchar(100) NULL COMMENT '一级分类code' AFTER `CATEGORYPARENTID`;