ALTER TABLE `trace_data`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `buyLink`;

ALTER TABLE `business_unit`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `isblacklist`;

ALTER TABLE `picefile_to_resource`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `RESOURCE_ID`;

ALTER TABLE `dishs_no`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `qiyeId`;

ALTER TABLE `waste_dispoa`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `qiyeId`;

ALTER TABLE `ledger_prepackno`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `qiyeId`;

ALTER TABLE `product`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `product_certification`;

ALTER TABLE `product_business_license`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `create_date`;

ALTER TABLE `member`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `status`;

ALTER TABLE `dishsno_to_resource`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `resource_id`;

ALTER TABLE `trace_data_product_name`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `barcode`;

ALTER TABLE `wdn_order_info`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `status`;

ALTER TABLE `product_barcode_to_qrcode`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `end_num`;

ALTER TABLE `mengniu_product_import_log`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `end_date`;

ALTER TABLE `mengniu_product_name`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `create_time`;

ALTER TABLE `mengniu_product_name_to_barcode`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `barcode`;

ALTER TABLE `sample_product_instance`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `sample_product_id`;

ALTER TABLE `sample_product`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `UNIT_ID`;

ALTER TABLE `sample_business_brand`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `business_unit_id`;

ALTER TABLE `test_result`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `suppliers_back_count`;

ALTER TABLE `product_recommend_url`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `identify`;

ALTER TABLE `sanitary_cert_pdf_to_resource`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `createDate`;

ALTER TABLE `business_unit2`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `origin`;

ALTER TABLE `t_meta_out_goods_info_copy`
ADD COLUMN `RECORD_INSERT_TIME`  timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP AFTER `HAS_INSPECTION_REPORT`;

