CREATE TABLE `deal_problem` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '序号',
  `province` varchar(100) DEFAULT NULL COMMENT '省',
  `city` varchar(100) DEFAULT NULL COMMENT '市',
  `counties` varchar(100) DEFAULT NULL COMMENT '区/县',
  `product_name` varchar(255) DEFAULT NULL COMMENT '产品名称',
  `business_name` varchar(200) DEFAULT NULL COMMENT '企业名称',
  `license_no` varchar(50) DEFAULT NULL COMMENT '营业执照',
  `barcode` varchar(100) DEFAULT NULL COMMENT '条形码',
  `product_time` datetime DEFAULT NULL COMMENT '产品生产日期',
  `problem_type` tinyint(3) DEFAULT '0' COMMENT '问题类型',
  `create_time` datetime DEFAULT NULL COMMENT '用户问题发现时间',
  `deal_time` datetime DEFAULT NULL COMMENT '企业处理时间',
  `request_deal_time` date DEFAULT NULL COMMENT '监管要求处理完成时间',
  `origin` tinyint(3) DEFAULT '0' COMMENT '信息来源：监管/终端/食安测',
  `deal_status` tinyint(3) DEFAULT '0' COMMENT '企业处理：已处理/未处理',
  `commit_status` tinyint(3) DEFAULT '0' COMMENT '管理员：提交企业/提交监管/忽略',
  `complain_status` tinyint(3) DEFAULT '0' COMMENT '投诉处理/新增投诉(1)/已提交投诉(2)/忽略(3)',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `longitude` double DEFAULT '0' COMMENT '经度',
  `latitude` double DEFAULT '0' COMMENT '纬度',
  `business_id` bigint(20) DEFAULT NULL COMMENT '企业ID',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8
