CREATE TABLE `destroy_record_to_resource` (
`ID`  bigint(20) NOT NULL AUTO_INCREMENT ,
`DESTROY_RECORD_ID`  bigint(20) NOT NULL COMMENT '销毁记录id' ,
`RESOURCE_ID`  bigint(20) NOT NULL COMMENT '资源id' ,
`INSERT_TIME`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据插入时间' ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='销毁记录资源对应表'
AUTO_INCREMENT=30
ROW_FORMAT=COMPACT
;