ALTER TABLE T_SYS_USER_ROLE ADD FOREIGN KEY (USER_ID) REFERENCES T_SYS_USER (USER_ID);
ALTER TABLE T_SYS_USER_ROLE ADD FOREIGN KEY (ROLE_ID) REFERENCES T_SYS_ROLE (ROLE_ID);
ALTER TABLE T_SYS_ROLE_PERMISSION ADD FOREIGN KEY (ROLE_ID) REFERENCES T_SYS_ROLE (ROLE_ID);
ALTER TABLE T_SYS_ROLE_PERMISSION ADD FOREIGN KEY (PERMISSION_ID) REFERENCES T_SYS_PERMISSION (PERMISSION_ID);
ALTER TABLE T_SYS_USER ADD FOREIGN KEY (ORGANIZATION_NAME) REFERENCES T_SYS_ORGANIZATION (ORGANIZATION_NAME);

COMMIT;