ALTER TABLE `t_sys_organization` ADD `CREATED_DATE` DATETIME DEFAULT NULL;
ALTER TABLE `t_sys_role` ADD `CREATED_DATE` DATETIME DEFAULT NULL;
ALTER TABLE `t_sys_permission` ADD `PERMISSION_URL` VARCHAR(500) DEFAULT NULL;
ALTER TABLE `t_sys_permission` ADD `PARENT` BIGINT(10) DEFAULT NULL;
ALTER TABLE `t_sys_permission` ADD `LOCALE_CODE` CHAR(5) DEFAULT 'zh_CN';
ALTER TABLE `t_sys_permission` ADD `DESCRIPTION` VARCHAR(255) DEFAULT NULL;
ALTER TABLE `t_sys_permission` ADD `CREATED_DATE` DATETIME DEFAULT NULL;

COMMIT;
