ALTER TABLE `t_sys_user` ADD `ORGANIZATION_NAME` VARCHAR(100) DEFAULT NULL;
ALTER TABLE `t_sys_user` ADD `REGISTER_DATE` DATETIME DEFAULT NULL;
ALTER TABLE `t_sys_user` ADD `LAST_LOGIN_DATE` DATETIME DEFAULT NULL;

DROP TABLE IF EXISTS `t_sys_organization`;
CREATE TABLE `t_sys_organization` (
	`ORGANIZATION_NAME` varchar(100) NOT NULL,
	`ORGANIZATION_ADDRESS` varchar(200) DEFAULT NULL,
	`COMMENTS` varchar(200) DEFAULT NULL,
	PRIMARY KEY(`ORGANIZATION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_sys_permission`;
CREATE TABLE `t_sys_permission` (
	`PERMISSION_ID` bigint(10) NOT NULL AUTO_INCREMENT,
	`PERMISSION_NAME` varchar(50) NOT NULL,
	PRIMARY KEY(`PERMISSION_ID`),
	UNIQUE KEY `PERMISSION_NAME` (`PERMISSION_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_sys_role`;
CREATE TABLE `t_sys_role` (
	`ROLE_ID` bigint(10) NOT NULL AUTO_INCREMENT,
	`ROLE_NAME` varchar(50) NOT NULL,
	PRIMARY KEY(`ROLE_ID`),
	UNIQUE KEY `ROLE_NAME` (`ROLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_sys_user_role`;
CREATE TABLE `t_sys_user_role` (
	`USER_ID` bigint(10) NOT NULL,
	`ROLE_ID` bigint(10) NOT NULL,
	PRIMARY KEY(`USER_ID`, `ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `t_sys_role_permission`;
CREATE TABLE `t_sys_role_permission` (
	`ROLE_ID` bigint(10) NOT NULL,
	`PERMISSION_ID` bigint(10) NOT NULL,
	PRIMARY KEY(`ROLE_ID`, `PERMISSION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;